### ISSUE TITLE
editing html file

### ISSUE THREAD

**Issue by W-i-n-7** [damienzonly/hfs-simple-editor#1]
i tried editing a html file it displays the html page inside the text editor 😂
![img](https://github.com/damienzonly/hfs-simple-editor/assets/90262580/8c60e462-0b95-4aea-b86e-b3077a7be142)

**Comment by W-i-n-7** [comment]
massive attachment... oops

**Comment by damienzonly** [comment]
well, i didn't see that coming :sweat_smile: , thank you very much for the feedback, i'll work on that

**Comment by W-i-n-7** [comment]
> well, i didn't see that coming 😅 , thank you very much for the feedback, i'll work on that

np

**Comment by damienzonly** [comment]
@W-i-n-7 i released version 1.3, let me know if the problem persists with html files

**Comment by W-i-n-7** [comment]
sorry took a while
it appears to be fixed now too

**Comment by damienzonly** [comment]
happy to hear that! thank you for the feedbacks
